### ISSUE TITLE
Not an issue but is there a way to output sidechain conformation to visualize the prediction?

### ISSUE THREAD

**Issue by bio-rat** [HannesStark/FlowSite#4]
Hi Stark,

Thank you for the amazing work! I have been using your work for my job of redesigning an enzyme active site. I watched your youtube video explaining FlowSite and that was helpful too but I am having trouble interpreting the result since there is no output structure to understand the conformation of the ligand and the residues around it. In the youtube video and the paper you had some figures that illustrates the output therefore I am asking how did you come up with that?

**Comment by HannesStark** [comment]
The conversion from torsion angles to 3D coordinates is not currently implemented. 
I would recommend using the openfold code for that https://github.com/aqlaboratory/openfold
