### ISSUE TITLE
error when loading model

### ISSUE THREAD

**Issue by zhouxiangxin1998** [HannesStark/FlowSite#5]
Hi Hannes,   

There is an error when running the test code (the recently released version) of FlowSite as follows:
```
RuntimeError: Error(s) in loading state_dict for FlowSiteModule:
        Missing key(s) in state_dict: "model.inv_embedder.virtual_atoms"
```

I think this may be caused by the modification of model codes in the recently released version.    
And the **first** version of your code works well.

**Comment by zhouxiangxin1998** [comment]
@HannesStark 
https://stackoverflow.com/questions/76516179/why-is-nn-parameter-not-being-saved-in-model-state-dict  
This may help.

**Comment by HannesStark** [comment]
THanks for pointing it out!
When you say it worked in the first version, do you mean that the exact same command (with the same weights) ran in the first commit of this repo?

**Comment by zhouxiangxin1998** [comment]
Hi Hannes,  
Thanks for your reply.    
The first version that I mentioned means your first commit.    
I tried the commands for testing flowsite and it worked.    
But I encountered a problem with loading model when I used your recent commit.

**Comment by HannesStark** [comment]
Thanks for brining this introduced mistake to my attention.
I fixed it, you will have to download the weights again.

(I also noticed that I had the unnecessary latest checkpoints in the weights download and removed those. So it should be half the size now :))

**Comment by zhouxiangxin1998** [comment]
@HannesStark   
Hi Hannes,   
There may be another problem with the training code.
Run the command of training FlowSite on PDBBind and the following error occurs:     
```
lightning.fabric.utilities.exceptions.MisconfigurationException: `ModelCheckpoint(monitor='val_accuracy')` could not find the monitored key in the returned metrics: ['trainer/global_step', 'epoch', 'fake_lig_ratio', 'step']. HINT: Did you call `log('val_
accuracy', value)` in the `LightningModule`?
```

**Comment by HannesStark** [comment]
Thanks for all the help! Seems that was a problem where I accidentally removed the logging during validation when I wrote the inference logging aggregation.
Fixed now.
